name: Python application

on:
  push:
    branches: [ "Prod" ]
  pull_request:
    branches: [ "Prod" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install requirements
      run: |
    - name: Test with pytest
      run: python app.py
